name: Deploy to ECR

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region:  us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
      run: |
        echo "============ Ruby Base ==============="
        docker pull ${ECR_REGISTRY}/nexoos-images/ruby-base:latest || true
        docker build -f ruby-base/Dockerfile -t ${ECR_REGISTRY}/nexoos-images/ruby-base:latest .
        docker push ${ECR_REGISTRY}/nexoos-images/ruby-base:latest
 
        echo "============ Ruby 2.5 ==============="
        docker build -f ruby/2.5.Dockerfile \
        --build-arg BASE_IMAGE=${ECR_REGISTRY}/nexoos-images/ruby-base:latest \
        -t ${ECR_REGISTRY}/nexoos-images/ruby:2.5 .
        docker push ${ECR_REGISTRY}/nexoos-images/ruby:2.5
 